allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense

cache_path: .licenses.ignored

ignored:

reviewed:
  npm:
    - actions/http-client
