name: "Licensed CI Rebuild"
description: "Wait a designated number of milliseconds"
inputs:
  github_token:
    description: "Access token to push license updates to GitHub"
    required: false
    default: ${{ github.token }}
  config_file:
    description: "Path to licensed configuration file"
    required: false
    default: ".licensed.yml"
  display_output:
    description: "Should licensed output be displayed in action logs"
    required: false
    default: "false"
  should_fail:
    description: "Should action fail if licenses for review are found"
    required: false
    default: "false"
  sns_topic:
    description: "AWS SNS Topic to push error logs to. Leave blank or 'false' to disable feature"
    required: false
    default: "false"
outputs:
  cache_log:
    description: "The output log of license caching"
  status_log:
    description: "The output log of license status checking"
runs:
  using: "node12"
  main: "dist/index.js"
